name: build
on: 
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir out
        touch build.sh
        bash build.sh | tee out/build.log
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: out
        path: out
